#!/usr/bin/env bash
#
# Makeplate 3dparty install script
#
# newScript is destination directory
#

scriptPath=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )


# Install file to dir
# arg1 local file to copy
# arg2 destination dir
mpInst() {
  dn=$(dirname $1)
	dst=$2/${dn}
	if [ ! -d ${dst} ]; then	
		mkdir -p $dst
	fi
	cp -rf ${scriptPath}/$1 $2/${dn}/.
}

mpInst src/def.h      $1
mpInst src/def_util.h $1
mpInst src/def_util.c $1

mpInst src/i2i.c $1
mpInst src/i2i.h $1

mpInst src/i2s.c $1
mpInst src/i2s.h $1

mpInst src/s2s.c $1
mpInst src/s2s.h $1


